server:
  port: 7070

spring:
  config:
    import: secrets.properties
  cloud:
    gateway:
      routes:
        - id: articles-route
          uri: ${ARTICLES_ROUTE_URI:http://localhost:8081}
          predicates:
            - Path=/articles/**
          filters:
            - PrefixPath=/api/v1
        - id: users-route
          uri: ${USERS_ROUTE_URI:http://localhost:8080}
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api/v1

application:
  jwt:
    jwks-uri: ${KSGR_JWKS_URI}